### PR TITLE
Batch improvements

### LINKED ISSUE #622: Better batch binding
We are over-using tuples a bit too much:
```rust
impl<'a, T: ShaderParam> Batch for (&'a mesh::Mesh<T::Resources>, mesh::Slice<T::Resources>,
&'a ProgramHandle<T::Resources>, &'a T, &'a DrawState)  {...}

impl<'a, T: ShaderParam> Batch for (&'a RefBatch<T>, &'a T, &'a Context<T::Resources>) {}
```

No, it doesn't look good on the user side either. And the error messages don't help you to figure out what's wrong. It would just say that your tuple doesn't implement `Batch` but will not answer, why.

First we need to use name-less structs here:
```rust
RefBatchFull<'a, T: ShaderParam>(&'a RefBatch<T>, &'a T, &'a Context<T::Resources>);
```

Second, we need to provide helper functions to construct them on site:
```rust
renderer.draw(context.bind(&batch, &data), &frame).unwrap();
```
instead of:
```rust
renderer.draw(&(&batch, &data, &context), &frame).unwrap();
```

### PR DESCRIPTION
**Pull request by kvark**
Closes #622, #620, #619

This PR doesn't break any API yet, because I was unable to use structures (lifetimes issues #614).
Also, I couldn't make `Context::bind()` to return a reference to the temporal batch. Perhaps, a task for future PRs.

### CODE REVIEW

File: src/render/batch.rs [hunk 1]
```diff
@@ -21,52 +21,22 @@ use std::num::from_uint;
...
-    MeshLink(mesh::LinkError),
-}
-
 /// An error occurring at batch creation
 #[derive(Clone, Debug, PartialEq)]
-pub enum BatchError {
+pub enum Error {
     /// Error connecting mesh attributes
-    Mesh(MeshError),
+    Mesh(mesh::Error),
```
Comment (csherratt) [inline src/render/batch.rs]: I like this.

File: src/render/mesh.rs [hunk 2]
```diff
@@ -226,15 +230,33 @@ pub struct Link {
 }
 
 impl Link {
+    /// Match mesh attributes against shader inputs, produce a mesh link.
+    /// Exposed to public to allow external `Batch` implementations to use it.
+    pub fn new<R: Resources>(mesh: &Mesh<R>, pinfo: &device::shade::ProgramInfo)
+                             -> Result<Link, Error> {
+        let mut indices = Vec::new();
+        for sat in pinfo.attributes.iter() {
+            match mesh.attributes.iter().enumerate()
```
Comment (csherratt) [inline src/render/mesh.rs]: I realize this was moving of code. But is this no N^2?

Comment (kvark) [inline src/render/mesh.rs]: It is `N^2`, yes, and we are doing it when constructing a batch, so it doesn't happen during rendering.

**Comment by csherratt** [comment]
It's harder to judge how the change effects code since the examples are not in `gfx-rs` any more. But otherwise this looks fine.

**Comment by kvark** [comment]
See the examples in https://github.com/gfx-rs/gfx_examples/pull/4
